FROM public.ecr.aws/lambda/python:3.11

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir --only-binary :all: \
    --trusted-host pypi.org \
    --trusted-host pypi.python.org \
    --trusted-host files.pythonhosted.org \
    boto3 \
    "pandas==2.2.3" \
    "pyarrow==17.0.0" \
    requests \
    "tzdata==2024.1" \
    python-dotenv

COPY src/mlb_total_bases_modeling/lambda/lambda_snapshot.py ${LAMBDA_TASK_ROOT}/
COPY src ${LAMBDA_TASK_ROOT}/src

CMD ["lambda_snapshot.lambda_handler"]
