"""
NCAAB Team Name Normalization Mapping

Maps The Odds API team names → ESPN team names.
ESPN is the source of truth (used for live game scores/status).

Built from:
- Historical Odds API data (109 unique teams from futures)
- Live Odds API data (51 games, 102 teams from line movement script output)
- ESPN API data (4 teams from today's scoreboard)
- Pattern analysis (abbreviations: St→State, Univ.→University, Miss→Mississippi)

Created: 2026-02-16
"""



# Complete mapping: Odds API → ESPN (all NCAAB teams)
# Generated from 365 teams in historical data
# 55 teams require normalization, 310 are identical
ODDS_API_TO_ESPN_NCAAB = {
    # ============================================================================
    # TEAMS REQUIRING NORMALIZATION (55 teams)
    # ============================================================================
    "Alabama St Hornets": "Alabama State Hornets",
    "Alcorn St Braves": "Alcorn State Braves",
    "Appalachian St Mountaineers": "Appalachian State Mountaineers",
    "Arizona St Sun Devils": "Arizona State Sun Devils",
    "Arkansas St Red Wolves": "Arkansas State Red Wolves",
    "Boston Univ. Terriers": "Boston University Terriers",
    "CSU Bakersfield Roadrunners": "Cal State Bakersfield Roadrunners",
    "CSU Fullerton Titans": "Cal State Fullerton Titans",
    "CSU Northridge Matadors": "Cal State Northridge Matadors",
    "Central Connecticut St Blue Devils": "Central Connecticut State Blue Devils",
    "Chicago St Cougars": "Chicago State Cougars",
    "Cleveland St Vikings": "Cleveland State Vikings",
    "Colorado St Rams": "Colorado State Rams",
    "Coppin St Eagles": "Coppin State Eagles",
    "Delaware St Hornets": "Delaware State Hornets",
    "East Tennessee St Buccaneers": "East Tennessee State Buccaneers",
    "Florida St Seminoles": "Florida State Seminoles",
    "Fresno St Bulldogs": "Fresno State Bulldogs",
    "Georgia St Panthers": "Georgia State Panthers",
    "Grambling St Tigers": "Grambling State Tigers",
    "Illinois St Redbirds": "Illinois State Redbirds",
    "Indiana St Sycamores": "Indiana State Sycamores",
    "Jackson St Tigers": "Jackson State Tigers",
    "Jacksonville St Gamecocks": "Jacksonville State Gamecocks",
    "Kansas St Wildcats": "Kansas State Wildcats",
    "Kennesaw St Owls": "Kennesaw State Owls",
    "Long Beach St 49ers": "Long Beach State 49ers",
    "Michigan St Spartans": "Michigan State Spartans",
    "Miss Valley St Delta Devils": "Mississippi Valley State Delta Devils",
    "Mississippi St Bulldogs": "Mississippi State Bulldogs",
    "Missouri St Bears": "Missouri State Bears",
    "Montana St Bobcats": "Montana State Bobcats",
    "Morehead St Eagles": "Morehead State Eagles",
    "Morgan St Bears": "Morgan State Bears",
    "Murray St Racers": "Murray State Racers",
    "New Mexico St Aggies": "New Mexico State Aggies",
    "Nicholls St Colonels": "Nicholls State Colonels",
    "Norfolk St Spartans": "Norfolk State Spartans",
    "North Dakota St Bison": "North Dakota State Bison",
    "Northwestern St Demons": "Northwestern State Demons",
    "Oklahoma St Cowboys": "Oklahoma State Cowboys",
    "Oregon St Beavers": "Oregon State Beavers",
    "Portland St Vikings": "Portland State Vikings",
    "SE Missouri St Redhawks": "SE Missouri State Redhawks",
    "Sacramento St Hornets": "Sacramento State Hornets",
    "Sam Houston St Bearkats": "Sam Houston State Bearkats",
    "San Diego St Aztecs": "San Diego State Aztecs",
    "San José St Spartans": "San José State Spartans",
    "South Carolina St Bulldogs": "South Carolina State Bulldogs",
    "South Dakota St Jackrabbits": "South Dakota State Jackrabbits",
    "Tennessee St Tigers": "Tennessee State Tigers",
    "Washington St Cougars": "Washington State Cougars",
    "Wichita St Shockers": "Wichita State Shockers",
    "Wright St Raiders": "Wright State Raiders",
    "Youngstown St Penguins": "Youngstown State Penguins",

    # ============================================================================
    # TEAMS WITH IDENTICAL NAMES (310 teams)
    # ============================================================================
    "Abilene Christian Wildcats": "Abilene Christian Wildcats",
    "Air Force Falcons": "Air Force Falcons",
    "Akron Zips": "Akron Zips",
    "Alabama A&M Bulldogs": "Alabama A&M Bulldogs",
    "Alabama Crimson Tide": "Alabama Crimson Tide",
    "Albany Great Danes": "Albany Great Danes",
    "American Eagles": "American Eagles",
    "Arizona Wildcats": "Arizona Wildcats",
    "Arkansas Razorbacks": "Arkansas Razorbacks",
    "Arkansas-Little Rock Trojans": "Arkansas-Little Rock Trojans",
    "Arkansas-Pine Bluff Golden Lions": "Arkansas-Pine Bluff Golden Lions",
    "Army Knights": "Army Knights",
    "Auburn Tigers": "Auburn Tigers",
    "Austin Peay Governors": "Austin Peay Governors",
    "BYU Cougars": "BYU Cougars",
    "Ball State Cardinals": "Ball State Cardinals",
    "Baylor Bears": "Baylor Bears",
    "Bellarmine Knights": "Bellarmine Knights",
    "Belmont Bruins": "Belmont Bruins",
    "Bethune-Cookman Wildcats": "Bethune-Cookman Wildcats",
    "Binghamton Bearcats": "Binghamton Bearcats",
    "Boise State Broncos": "Boise State Broncos",
    "Boston College Eagles": "Boston College Eagles",
    "Bowling Green Falcons": "Bowling Green Falcons",
    "Bradley Braves": "Bradley Braves",
    "Brown Bears": "Brown Bears",
    "Bryant Bulldogs": "Bryant Bulldogs",
    "Bucknell Bison": "Bucknell Bison",
    "Buffalo Bulls": "Buffalo Bulls",
    "Butler Bulldogs": "Butler Bulldogs",
    "Cal Baptist Lancers": "Cal Baptist Lancers",
    "Cal Poly Mustangs": "Cal Poly Mustangs",
    "California Golden Bears": "California Golden Bears",
    "Campbell Fighting Camels": "Campbell Fighting Camels",
    "Canisius Golden Griffins": "Canisius Golden Griffins",
    "Central Arkansas Bears": "Central Arkansas Bears",
    "Central Michigan Chippewas": "Central Michigan Chippewas",
    "Charleston Cougars": "Charleston Cougars",
    "Charleston Southern Buccaneers": "Charleston Southern Buccaneers",
    "Charlotte 49ers": "Charlotte 49ers",
    "Chattanooga Mocs": "Chattanooga Mocs",
    "Cincinnati Bearcats": "Cincinnati Bearcats",
    "Clemson Tigers": "Clemson Tigers",
    "Coastal Carolina Chanticleers": "Coastal Carolina Chanticleers",
    "Colgate Raiders": "Colgate Raiders",
    "Colorado Buffaloes": "Colorado Buffaloes",
    "Columbia Lions": "Columbia Lions",
    "Cornell Big Red": "Cornell Big Red",
    "Creighton Bluejays": "Creighton Bluejays",
    "Dartmouth Big Green": "Dartmouth Big Green",
    "Davidson Wildcats": "Davidson Wildcats",
    "Dayton Flyers": "Dayton Flyers",
    "DePaul Blue Demons": "DePaul Blue Demons",
    "Delaware Blue Hens": "Delaware Blue Hens",
    "Denver Pioneers": "Denver Pioneers",
    "Detroit Mercy Titans": "Detroit Mercy Titans",
    "Drake Bulldogs": "Drake Bulldogs",
    "Drexel Dragons": "Drexel Dragons",
    "Duke Blue Devils": "Duke Blue Devils",
    "Duquesne Dukes": "Duquesne Dukes",
    "East Carolina Pirates": "East Carolina Pirates",
    "East Texas A&M Lions": "East Texas A&M Lions",
    "Eastern Illinois Panthers": "Eastern Illinois Panthers",
    "Eastern Kentucky Colonels": "Eastern Kentucky Colonels",
    "Eastern Michigan Eagles": "Eastern Michigan Eagles",
    "Eastern Washington Eagles": "Eastern Washington Eagles",
    "Elon Phoenix": "Elon Phoenix",
    "Evansville Purple Aces": "Evansville Purple Aces",
    "Fairfield Stags": "Fairfield Stags",
    "Fairleigh Dickinson Knights": "Fairleigh Dickinson Knights",
    "Florida A&M Rattlers": "Florida A&M Rattlers",
    "Florida Atlantic Owls": "Florida Atlantic Owls",
    "Florida Gators": "Florida Gators",
    "Florida Gulf Coast Eagles": "Florida Gulf Coast Eagles",
    "Florida Int'l Golden Panthers": "Florida Int'l Golden Panthers",
    "Fordham Rams": "Fordham Rams",
    "Fort Wayne Mastodons": "Fort Wayne Mastodons",
    "Furman Paladins": "Furman Paladins",
    "GW Revolutionaries": "GW Revolutionaries",
    "Gardner-Webb Bulldogs": "Gardner-Webb Bulldogs",
    "George Mason Patriots": "George Mason Patriots",
    "Georgetown Hoyas": "Georgetown Hoyas",
    "Georgia Bulldogs": "Georgia Bulldogs",
    "Georgia Southern Eagles": "Georgia Southern Eagles",
    "Georgia Tech Yellow Jackets": "Georgia Tech Yellow Jackets",
    "Gonzaga Bulldogs": "Gonzaga Bulldogs",
    "Grand Canyon Antelopes": "Grand Canyon Antelopes",
    "Green Bay Phoenix": "Green Bay Phoenix",
    "Hampton Pirates": "Hampton Pirates",
    "Harvard Crimson": "Harvard Crimson",
    "Hawai'i Rainbow Warriors": "Hawai'i Rainbow Warriors",
    "High Point Panthers": "High Point Panthers",
    "Hofstra Pride": "Hofstra Pride",
    "Holy Cross Crusaders": "Holy Cross Crusaders",
    "Houston Christian Huskies": "Houston Christian Huskies",
    "Houston Cougars": "Houston Cougars",
    "Howard Bison": "Howard Bison",
    "IUPUI Jaguars": "IUPUI Jaguars",
    "Idaho State Bengals": "Idaho State Bengals",
    "Idaho Vandals": "Idaho Vandals",
    "Illinois Fighting Illini": "Illinois Fighting Illini",
    "Incarnate Word Cardinals": "Incarnate Word Cardinals",
    "Indiana Hoosiers": "Indiana Hoosiers",
    "Iona Gaels": "Iona Gaels",
    "Iowa Hawkeyes": "Iowa Hawkeyes",
    "Iowa State Cyclones": "Iowa State Cyclones",
    "Jacksonville Dolphins": "Jacksonville Dolphins",
    "James Madison Dukes": "James Madison Dukes",
    "Kansas Jayhawks": "Kansas Jayhawks",
    "Kent State Golden Flashes": "Kent State Golden Flashes",
    "Kentucky Wildcats": "Kentucky Wildcats",
    "LIU Sharks": "LIU Sharks",
    "LSU Tigers": "LSU Tigers",
    "La Salle Explorers": "La Salle Explorers",
    "Lafayette Leopards": "Lafayette Leopards",
    "Lamar Cardinals": "Lamar Cardinals",
    "Le Moyne Dolphins": "Le Moyne Dolphins",
    "Lehigh Mountain Hawks": "Lehigh Mountain Hawks",
    "Liberty Flames": "Liberty Flames",
    "Lindenwood Lions": "Lindenwood Lions",
    "Lipscomb Bisons": "Lipscomb Bisons",
    "Longwood Lancers": "Longwood Lancers",
    "Louisiana Ragin' Cajuns": "Louisiana Ragin' Cajuns",
    "Louisiana Tech Bulldogs": "Louisiana Tech Bulldogs",
    "Louisville Cardinals": "Louisville Cardinals",
    "Loyola (Chi) Ramblers": "Loyola (Chi) Ramblers",
    "Loyola (MD) Greyhounds": "Loyola (MD) Greyhounds",
    "Loyola Marymount Lions": "Loyola Marymount Lions",
    "Maine Black Bears": "Maine Black Bears",
    "Manhattan Jaspers": "Manhattan Jaspers",
    "Marist Red Foxes": "Marist Red Foxes",
    "Marquette Golden Eagles": "Marquette Golden Eagles",
    "Marshall Thundering Herd": "Marshall Thundering Herd",
    "Maryland Terrapins": "Maryland Terrapins",
    "Maryland-Eastern Shore Hawks": "Maryland-Eastern Shore Hawks",
    "Massachusetts Minutemen": "Massachusetts Minutemen",
    "McNeese Cowboys": "McNeese Cowboys",
    "Memphis Tigers": "Memphis Tigers",
    "Mercer Bears": "Mercer Bears",
    "Mercyhurst Lakers": "Mercyhurst Lakers",
    "Merrimack Warriors": "Merrimack Warriors",
    "Miami (OH) RedHawks": "Miami (OH) RedHawks",
    "Miami Hurricanes": "Miami Hurricanes",
    "Michigan Wolverines": "Michigan Wolverines",
    "Middle Tennessee Blue Raiders": "Middle Tennessee Blue Raiders",
    "Milwaukee Panthers": "Milwaukee Panthers",
    "Minnesota Golden Gophers": "Minnesota Golden Gophers",
    "Missouri Tigers": "Missouri Tigers",
    "Monmouth Hawks": "Monmouth Hawks",
    "Montana Grizzlies": "Montana Grizzlies",
    "Mt. St. Mary's Mountaineers": "Mt. St. Mary's Mountaineers",
    "N Colorado Bears": "N Colorado Bears",
    "NC State Wolfpack": "NC State Wolfpack",
    "NJIT Highlanders": "NJIT Highlanders",
    "Navy Midshipmen": "Navy Midshipmen",
    "Nebraska Cornhuskers": "Nebraska Cornhuskers",
    "Nevada Wolf Pack": "Nevada Wolf Pack",
    "New Hampshire Wildcats": "New Hampshire Wildcats",
    "New Haven Chargers": "New Haven Chargers",
    "New Mexico Lobos": "New Mexico Lobos",
    "New Orleans Privateers": "New Orleans Privateers",
    "Niagara Purple Eagles": "Niagara Purple Eagles",
    "North Alabama Lions": "North Alabama Lions",
    "North Carolina A&T Aggies": "North Carolina A&T Aggies",
    "North Carolina Central Eagles": "North Carolina Central Eagles",
    "North Carolina Tar Heels": "North Carolina Tar Heels",
    "North Dakota Fighting Hawks": "North Dakota Fighting Hawks",
    "North Florida Ospreys": "North Florida Ospreys",
    "North Texas Mean Green": "North Texas Mean Green",
    "Northeastern Huskies": "Northeastern Huskies",
    "Northern Arizona Lumberjacks": "Northern Arizona Lumberjacks",
    "Northern Illinois Huskies": "Northern Illinois Huskies",
    "Northern Iowa Panthers": "Northern Iowa Panthers",
    "Northern Kentucky Norse": "Northern Kentucky Norse",
    "Northwestern Wildcats": "Northwestern Wildcats",
    "Notre Dame Fighting Irish": "Notre Dame Fighting Irish",
    "Oakland Golden Grizzlies": "Oakland Golden Grizzlies",
    "Ohio Bobcats": "Ohio Bobcats",
    "Ohio State Buckeyes": "Ohio State Buckeyes",
    "Oklahoma Sooners": "Oklahoma Sooners",
    "Old Dominion Monarchs": "Old Dominion Monarchs",
    "Ole Miss Rebels": "Ole Miss Rebels",
    "Omaha Mavericks": "Omaha Mavericks",
    "Oral Roberts Golden Eagles": "Oral Roberts Golden Eagles",
    "Oregon Ducks": "Oregon Ducks",
    "Pacific Tigers": "Pacific Tigers",
    "Penn State Nittany Lions": "Penn State Nittany Lions",
    "Pennsylvania Quakers": "Pennsylvania Quakers",
    "Pepperdine Waves": "Pepperdine Waves",
    "Pittsburgh Panthers": "Pittsburgh Panthers",
    "Portland Pilots": "Portland Pilots",
    "Prairie View Panthers": "Prairie View Panthers",
    "Presbyterian Blue Hose": "Presbyterian Blue Hose",
    "Princeton Tigers": "Princeton Tigers",
    "Providence Friars": "Providence Friars",
    "Purdue Boilermakers": "Purdue Boilermakers",
    "Queens University Royals": "Queens University Royals",
    "Quinnipiac Bobcats": "Quinnipiac Bobcats",
    "Radford Highlanders": "Radford Highlanders",
    "Rhode Island Rams": "Rhode Island Rams",
    "Rice Owls": "Rice Owls",
    "Richmond Spiders": "Richmond Spiders",
    "Rider Broncs": "Rider Broncs",
    "Robert Morris Colonials": "Robert Morris Colonials",
    "Rutgers Scarlet Knights": "Rutgers Scarlet Knights",
    "SE Louisiana Lions": "SE Louisiana Lions",
    "SIU-Edwardsville Cougars": "SIU-Edwardsville Cougars",
    "SMU Mustangs": "SMU Mustangs",
    "Sacred Heart Pioneers": "Sacred Heart Pioneers",
    "Saint Joseph's Hawks": "Saint Joseph's Hawks",
    "Saint Louis Billikens": "Saint Louis Billikens",
    "Saint Mary's Gaels": "Saint Mary's Gaels",
    "Saint Peter's Peacocks": "Saint Peter's Peacocks",
    "Samford Bulldogs": "Samford Bulldogs",
    "San Diego Toreros": "San Diego Toreros",
    "San Francisco Dons": "San Francisco Dons",
    "Santa Clara Broncos": "Santa Clara Broncos",
    "Seattle Redhawks": "Seattle Redhawks",
    "Seton Hall Pirates": "Seton Hall Pirates",
    "Siena Saints": "Siena Saints",
    "South Alabama Jaguars": "South Alabama Jaguars",
    "South Carolina Gamecocks": "South Carolina Gamecocks",
    "South Carolina Upstate Spartans": "South Carolina Upstate Spartans",
    "South Dakota Coyotes": "South Dakota Coyotes",
    "South Florida Bulls": "South Florida Bulls",
    "Southern Illinois Salukis": "Southern Illinois Salukis",
    "Southern Indiana Screaming Eagles": "Southern Indiana Screaming Eagles",
    "Southern Jaguars": "Southern Jaguars",
    "Southern Miss Golden Eagles": "Southern Miss Golden Eagles",
    "Southern Utah Thunderbirds": "Southern Utah Thunderbirds",
    "St. Bonaventure Bonnies": "St. Bonaventure Bonnies",
    "St. Francis (PA) Red Flash": "St. Francis (PA) Red Flash",
    "St. John's Red Storm": "St. John's Red Storm",
    "St. Thomas (MN) Tommies": "St. Thomas (MN) Tommies",
    "Stanford Cardinal": "Stanford Cardinal",
    "Stephen F. Austin Lumberjacks": "Stephen F. Austin Lumberjacks",
    "Stetson Hatters": "Stetson Hatters",
    "Stonehill Skyhawks": "Stonehill Skyhawks",
    "Stony Brook Seawolves": "Stony Brook Seawolves",
    "Syracuse Orange": "Syracuse Orange",
    "TCU Horned Frogs": "TCU Horned Frogs",
    "Tarleton State Texans": "Tarleton State Texans",
    "Temple Owls": "Temple Owls",
    "Tenn-Martin Skyhawks": "Tenn-Martin Skyhawks",
    "Tennessee Tech Golden Eagles": "Tennessee Tech Golden Eagles",
    "Tennessee Volunteers": "Tennessee Volunteers",
    "Texas A&M Aggies": "Texas A&M Aggies",
    "Texas A&M-CC Islanders": "Texas A&M-CC Islanders",
    "Texas Longhorns": "Texas Longhorns",
    "Texas Southern Tigers": "Texas Southern Tigers",
    "Texas State Bobcats": "Texas State Bobcats",
    "Texas Tech Red Raiders": "Texas Tech Red Raiders",
    "The Citadel Bulldogs": "The Citadel Bulldogs",
    "Toledo Rockets": "Toledo Rockets",
    "Towson Tigers": "Towson Tigers",
    "Troy Trojans": "Troy Trojans",
    "Tulane Green Wave": "Tulane Green Wave",
    "Tulsa Golden Hurricane": "Tulsa Golden Hurricane",
    "UAB Blazers": "UAB Blazers",
    "UC Davis Aggies": "UC Davis Aggies",
    "UC Irvine Anteaters": "UC Irvine Anteaters",
    "UC Riverside Highlanders": "UC Riverside Highlanders",
    "UC San Diego Tritons": "UC San Diego Tritons",
    "UC Santa Barbara Gauchos": "UC Santa Barbara Gauchos",
    "UCF Knights": "UCF Knights",
    "UCLA Bruins": "UCLA Bruins",
    "UConn Huskies": "UConn Huskies",
    "UIC Flames": "UIC Flames",
    "UL Monroe Warhawks": "UL Monroe Warhawks",
    "UMBC Retrievers": "UMBC Retrievers",
    "UMKC Kangaroos": "UMKC Kangaroos",
    "UMass Lowell River Hawks": "UMass Lowell River Hawks",
    "UNC Asheville Bulldogs": "UNC Asheville Bulldogs",
    "UNC Greensboro Spartans": "UNC Greensboro Spartans",
    "UNC Wilmington Seahawks": "UNC Wilmington Seahawks",
    "UNLV Rebels": "UNLV Rebels",
    "USC Trojans": "USC Trojans",
    "UT Rio Grande Valley Vaqueros": "UT Rio Grande Valley Vaqueros",
    "UT-Arlington Mavericks": "UT-Arlington Mavericks",
    "UTEP Miners": "UTEP Miners",
    "UTSA Roadrunners": "UTSA Roadrunners",
    "Utah State Aggies": "Utah State Aggies",
    "Utah Tech Trailblazers": "Utah Tech Trailblazers",
    "Utah Utes": "Utah Utes",
    "Utah Valley Wolverines": "Utah Valley Wolverines",
    "VCU Rams": "VCU Rams",
    "VMI Keydets": "VMI Keydets",
    "Valparaiso Beacons": "Valparaiso Beacons",
    "Vanderbilt Commodores": "Vanderbilt Commodores",
    "Vermont Catamounts": "Vermont Catamounts",
    "Villanova Wildcats": "Villanova Wildcats",
    "Virginia Cavaliers": "Virginia Cavaliers",
    "Virginia Tech Hokies": "Virginia Tech Hokies",
    "Wagner Seahawks": "Wagner Seahawks",
    "Wake Forest Demon Deacons": "Wake Forest Demon Deacons",
    "Washington Huskies": "Washington Huskies",
    "Weber State Wildcats": "Weber State Wildcats",
    "West Georgia Wolves": "West Georgia Wolves",
    "West Virginia Mountaineers": "West Virginia Mountaineers",
    "Western Carolina Catamounts": "Western Carolina Catamounts",
    "Western Illinois Leathernecks": "Western Illinois Leathernecks",
    "Western Kentucky Hilltoppers": "Western Kentucky Hilltoppers",
    "Western Michigan Broncos": "Western Michigan Broncos",
    "William & Mary Tribe": "William & Mary Tribe",
    "Winthrop Eagles": "Winthrop Eagles",
    "Wisconsin Badgers": "Wisconsin Badgers",
    "Wofford Terriers": "Wofford Terriers",
    "Wyoming Cowboys": "Wyoming Cowboys",
    "Xavier Musketeers": "Xavier Musketeers",
    "Yale Bulldogs": "Yale Bulldogs",
}


# Validation assertions (run at import time)
assert len(ODDS_API_TO_ESPN_NCAAB) == 365, \
    f"Expected 365 total NCAAB teams, got {len(ODDS_API_TO_ESPN_NCAAB)}"

# Count teams with different names (key != value)
differences_count = sum(1 for k, v in ODDS_API_TO_ESPN_NCAAB.items() if k != v)
assert differences_count == 55, \
    f"Expected 55 teams with different names, got {differences_count}"


def normalize_ncaab_team_name(odds_api_name: str) -> str:
    """
    Normalize NCAAB team name from The Odds API format to ESPN format.
    
    Args:
        odds_api_name: Team name from The Odds API
        
    Returns:
        Normalized team name matching ESPN format
    """
    # Check exact mapping first
    if odds_api_name in ODDS_API_TO_ESPN_NCAAB:
        return ODDS_API_TO_ESPN_NCAAB[odds_api_name]
    
    # If not in mapping, return as-is (most teams are identical)
    return odds_api_name
